### ISSUE TITLE
Give a exact count of how many whacking sticks, TNTs etc the user has in navigation (Stack the items to display a true count).

### ISSUE THREAD

**Issue by fihgus** [fihgus/McMurder-Issue-Tracking#22]
Give a exact count of how many whacking sticks, TNTs etc the user has in navigation (Stack the items to display a true count).

**Comment by fihgus** [comment]
Limited by Stack maximum size.

**Comment by gdahl** [comment]
If items purchased exceed 64 (Max Value), the number should not reduce in value until items reach below 64. If they purchase more items, this number will max back out at 64.
