### ISSUE TITLE
RedStone Blood Trail (Dragging Dead Body) blocking items

### ISSUE THREAD

**Issue by gdahl** [fihgus/McMurder-Issue-Tracking#27]
1) The redstone left by dragging the entity prevents users from picking up items that randomly spawn where redstone exists. 

2) Unable to place landmines (pressure plates) or wool where redstone exists.

**Comment by fihgus** [comment]
you can not place stuff on redstone.
Option here is to mark blood trail last for a while and remove itself.  let me know if you want to do that.

**Comment by gdahl** [comment]
Yeah, let's vanish blood trail within 30 seconds of being laid down.
