### ISSUE TITLE
Scrap used as Ammo for bow

### ISSUE THREAD

**Issue by gdahl** [fihgus/McMurder-Issue-Tracking#41]
Just to keep things simple and isolated (So we don't have a nav bar full of unnecessary items), only spawn scraps.  If a guy is a gunner (Gun/Bow), then scrap picked up will be used as ammunition, rather its for a gun or bow.  No need to spawn arrows with scrap, as it just eats up nav space for useful items.

**Comment by fihgus** [comment]
can not modify bow ammo, else it lose the pull bow animation.
