### ISSUE TITLE
Block Disguise (With Armor)

### ISSUE THREAD

**Issue by gdahl** [fihgus/McMurder-Issue-Tracking#47]
![bug](https://cloud.githubusercontent.com/assets/2532624/12818060/cd2c280c-cb1a-11e5-9127-b51163c44f36.png)

**Comment by gdahl** [comment]
This disguising system is really buggy. Can we just make it so that the murderer disguises as another player in the game? (No chat disguising.. Just character disguising).

**Comment by gdahl** [comment]
Which includes changing the nametag as well.

**Comment by fihgus** [comment]
It's invisible potion man.



On Thu, Feb 4, 2016 at 6:42 AM -0800, "gdahl" <notifications@github.com<mailto:notifications@github.com>> wrote:


Which includes changing the nametag as well.

-

**Comment by fihgus** [comment]
I thought I told you about how player needs to remember removing thier equipment.



On Thu, Feb 4, 2016 at 6:42 AM -0800, "gdahl" <notifications@github.com<mailto:notifications@github.com>> wrote:


Which includes changing the nametag as well.

-

**Comment by gdahl** [comment]
Well, it's not going to work out well as most people will have some sort of armor on. So, it defeats the purpose if the armor also shows. Therefore, changing the concept (marking it as enhancement) and using disguise to disguise as another play might be more interesting and less buggy.

And no, you didn't tell me about removing the armor.. but we want the armor to be locked on unless they set it to unset from the menu.

**Comment by fihgus** [comment]
I can make it so the effect remove/hide their armor for them, but letting them disguise as another player will not be easy for us, as far as i dig into libdisguise's code, they have a fake player entity following the actual player, while the player is hided from everyone, this will mess up all the event, so we could not use that method.



On Thu, Feb 4, 2016 at 8:35 AM -0800, "gdahl" <notifications@github.com<mailto:notifications@github.com>> wrote:


Well, it's not going to work out well as most people will have some sort of armor on. So, it defeats the purpose if the armor also shows. Therefore, changing the concept (marking it as enhancement) and using disguise to disguise as another play might be more interesting and less buggy.

And no, you didn't tell me about removing the armor.. but we want the armor to be locked on unless they set it to unset from the menu.

-

**Comment by fihgus** [comment]
stealth now will return the item if the block player is standing on can
not be disguised.
stealth now remove player armor for them, and give them back when player
exist stealth mode.
