### ISSUE TITLE
Blood left by entity be powered (redstone)

### ISSUE THREAD

**Issue by gdahl** [fihgus/McMurder-Issue-Tracking#48]
![enhancement](https://cloud.githubusercontent.com/assets/2532624/12819733/d4521fe0-cb21-11e5-852a-63ebace32376.png)

**Comment by fihgus** [comment]
They are redstone, what else do you think is going to happen?

**Comment by gdahl** [comment]
I forgot to provide description on this request.  Was going to see if we could activate the effect on the redstone trail in order.. to give it more of a visual demonstration to the players.

**Comment by fihgus** [comment]
no, I can power them on in one tick, but next tick they will be automatically powered off by the server.
